name: 🐛 Reportar un error
description: Reportar un fallo relacionado con funcionamiento de app
labels: [ "Bug"]
body:
  - type: markdown
    attributes:
      value: |
         ### ❗️ Lee esto antes de crear issue:         
         - **Proporcione la mayor cantidad de detalles posible:** registros de errores, capturas de pantalla, su configuración exacta.
         - **Consulta documentación de app** - confirma que está bien configurado según documentación http://sdesgh01:8080/extensiones/pte/wintc/
  - type: textarea
    id: what-happened
    attributes:
      label: Descripción del Bug
      description: Proporciona una descripción clara y concisa del fallo
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamiento esperado
      description: Proporciona una descripción clara y concisa de lo que esperabas que ocurriera.
    validations:
      required: false
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Pasos para reproducir
      description: Pasos para reproducir el comportamiento
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '....'
        3. Desplazarse hacia '....'
        4. Ver error
    validations:
      required: true
  - type: input
    id: wintc-version
    attributes:
      label: Versión de app
      description: Indica versión de app
      placeholder: "24.11.24.687"
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Versión de Windows
      placeholder: "Windows 11"
    validations:
      required: true
  - type: input
    id: customer
    attributes:
      label: En que cliente ha  Indique 0 si es interno (LIDER).
      placeholder: "Sport Lifestyle"
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Log de error "Stack trace"
      description: Copia trazablidad si dispone de log error registrado en **Visor de eventos**
    validations:
      required: false      
