name:  Reportar un error
description: Reportar un fallo relacionado con funcionamiento de app
labels: [ "Bug"]
body:
  - type: markdown
    attributes:
      value: |
         ### 锔 Lee esto antes de crear issue:         
         - **Proporcione la mayor cantidad de detalles posible:** registros de errores, capturas de pantalla, su configuraci贸n exacta.
         - **Consulta documentaci贸n de app** - confirma que est谩 bien configurado seg煤n documentaci贸n http://sdesgh01:8080/extensiones/pte/wintc/
  - type: textarea
    id: what-happened
    attributes:
      label: Descripci贸n del Bug
      description: Proporciona una descripci贸n clara y concisa del fallo
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamiento esperado
      description: Proporciona una descripci贸n clara y concisa de lo que esperabas que ocurriera.
    validations:
      required: false
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Para Reproducir
      description: Pasos para reproducir el comportamiento:
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '....'
        3. Desplazarse hacia '....'
        4. Ver error
    validations:
      required: true
  - type: input
    id: prestashop-version
    attributes:
      label: PrestaShop version(s) where the bug happened
      description: If the issue concerns upgrade, specify which versions you upgrading FROM and upgrading TO
      placeholder: "e.g., 1.7.5.2 or 1.7.8.0"
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP version(s) where the bug happened
      placeholder: "e.g., 7.1 or 8.0"
    validations:
      required: false
  - type: input
    id: module
    attributes:
      label: If your bug is related to a module, specify its name and its version
      placeholder: "e.g., ps_facetedsearch v7.0"
    validations:
      required: false
  - type: input
    id: sponsor-company
    attributes:
      label: Your company or customer's name goes here (if applicable).
    validations:
      required: false
