blank_issues_enabled: false
contact_links:
  - name: 🚀 Documentación de app
    url: http://sdesgh01:8080/extensiones/pte/wintc/
    about: Describe paso por paso instalacion, configuración de app y consultas API
