name: ⚙️ [INTERNO] Arquitectura y diseño de la solución
description: Proponer cambio interno -> CI/CD, dependencias NuGet, test automatizados, seguridad, etc. Cualquier otro cambio que no afecta la parte lógica de APP.
labels: [ "Mejora"]
projects: ["VadymPatuk/3"]
body:
  - type: textarea
    id: request-reason
    attributes:
      label: Motivo de la solicitud
      description: Proporciona motivo de la solicitud. 
      placeholder: Con este cambio será sustituida libreria obsoleta de API ...
    validations:
      required: true
  - type: textarea
    id: request-behavior
    attributes:
      label: Descripción de la solicitud
      description: Proporciona una descripción clara de la solicitud
      placeholder: Incrementar versión de servidor Kestrel para aceptar solicitud HTTP/3 ...
    validations:
      required: true
  - type: dropdown
    id: module
    attributes:
      label: Módulos afectados
      description: Seleccione módulos afectados
      multiple: true
      options:
        - Báscula
        - Fichero
        - Impresora
        - Repetidor
        - FTP
    validations:
      required: false      
  - type: textarea
    id: request-example
    attributes:
      label: Ejemplo de mejora
      description: Ejemplo propuesto para incorporar mejora -> Referencia a un artículo web, ejemplo de nuevo código, etc.      
    validations:
      required: false  
